databases:
  - name: alex-test
    databaseName: alex-test
    user: alex_test

services:
  - type: web
    name: alex-test
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: ALEX_TEST_DATABASE_URL
        fromDatabase:
          name: alex-test
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false